### ISSUE TITLE
Non prefix mode

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/properties#1]
Ist es bewusst möglich dass man ohne prefix arbeiten kann? Soll man core properties überschreiben können? Ich vermute damit kann man sich versehentlich große probleme bereiten...

Sollte der prefix pflicht sein?

**Comment by gharlan** [comment]
Ich würde ehrlich gesagt gar nicht in `rex::setProperty` schreiben, sondern eher mit Addon-Properties arbeiten.
So in der Art:

```php
$properties = rex_addon::get('properties');
$properties->getProperty('foo');
```

Letztlich würde ich aber auch das nicht machen, sondern direkt mit rex_config arbeiten. Schon beim Speichern würde ich es nicht in einem einzelnen rex_config-Feld speichern, sondern die "Properties" alle einzeln als Config-Werte dieses Addons.
Und dann so in der Art nutzen:

```php
$properties = rex_addon::get('properties');
$properties->getConfig('foo');
```

Falls man das so macht, wäre dann allerdings die Frage ob "properties" noch der richtige Addonname wäre.

**Comment by aeberhard** [comment]
@gharlan @staabm 
Hallo Gregor und Markus,

habe jetzt noch einmal gründlich überarbeitet.

- Alternative Schreibweise analog ini-Dateien ist jetzt auch möglich, für einige vielleicht besser zu lesen
- Readme.md erweitert, schaut da erst mal rein :)
- bestehende Properties werden nicht überschrieben
- Prüfung auf bestehende/doppelte Properties beim speichern

Ich finde man sollte die genialen bestehenden Funktionen setProperty/getProperty nicht noch durch
zusätzliche Klassen oder ähnliches künstlich aufbohren.
Das ganze sollte ganz einfach sein und wird ja von Programmierern verwendet, die sollten damit gut
klar kommen.

Und ja, ich kenne auch parse_ini_string :) Das ganze ist mir aber zu restriktiv genau so wie Yaml.
Hier wird auf ganz einfache Weise geparsed, und ganz einfache Syntax zum eingeben!
Vor allem darauf lag auch mein Fokus, einfach, wenig Code, aber viele Vorteile.

Für mich passt das so!

**Comment by aeberhard** [comment]
Close auch hier ...
