### ISSUE TITLE
Api zur Verfügung stellen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/properties#2]
Das Abfragen von properties erzeugt aktuell relativ langen code (prefix+key) und fühlt sich auch nicht 100% intuitiv an. Bei der definition soll prefix und key getrennt sein, beim abfragen soll man diese kombinieren.

Ich würde eine separate api anbieten wie man ebenfalls prefix und key separat angibt, somit hat man auch weniger code, z.b.

```php
$props = new rex_property_bundle(„mein prefix“);
If( $props->property(„mein key“) == 3) {
}
```

Über die bezeichner darf/kann man natürlich noch gerne diskutieren, ist nur ein bespiel.
Es würde sich vermutlich anbieten möglichst kurze bezeichner zu haben...

Als technischen mechanismus zum speichern der properties kann ja weiterhin rex::get/setPropertiesj) verwendet werden vom addon im Hintergrund.

**Comment by aeberhard** [comment]
@staabm die Schreibweise `REX_PROPERTY[key=HalloText]` in Modulen/Templates ist auch möglich!
