### ISSUE TITLE
data-codemirror-mode in textarea / ReferenceError

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/properties#5]
HI,
pages/system.properties.php
verwendet von Haus aus die Einstellung des codemirrors in der textarea. Wenn jemand  unter System/Customizer den Codemirror deaktiviert hat, wirft es im Properties AddOn Fehler und die Darstellung (Redaxo Logo) stimmt leider auch nicht mehr (?)

ReferenceError: CodeMirror is not defined
![properties-errror](https://user-images.githubusercontent.com/189407/43080080-26aa5b08-8e8f-11e8-912c-7bd907c87307.png)

Evtl braucht man hier auch gar kein CodeMirror - da eh nur plain text reingeschrieben werden sollte (oder?)

Danke. Gruß Christian

**Comment by aeberhard** [comment]
Hallo Christian @darwin26 , welche Versionen nutzt Du denn?
properties selbst hat kein JavaScript.
Und Codemirror wird verwendet wg. den Zeilennummern in den Fehlermeldungen und auch die Hervorhebung bei der Syntax ala ini-Dateien.

**Comment by darwin26** [comment]
Hallo Andreas,
die aktuelle Version ausm Installer.

> Und Codemirror wird verwendet wg. den Zeilennummern in den Fehlermeldungen und auch die Hervorhebung bei der Syntax ala ini-Dateien.
jep. soweit ja richtig, nur wenn jemand s/w benutzt ohne SyntaxHighlighter (codemirror), dann wirfts halt den Fehler. Also, wenn man das Häckchen nicht gesetzt hat:
![00012](https://user-images.githubusercontent.com/189407/43269319-deb8e9de-90f2-11e8-86c9-b87dc28ab9bf.png)

eigentlich ja egal, und wäre mir nicht aufgefallem ... erst, as das Redaxo Logo dadurch verändert wird/wurde  (siehe screenshot weiter oben) ...

----
andere Frage:
Wenn man Properties setzt und verwendet bool (true/false),
dann werden diese als 'string' übermittelt. ist das generell so oder kann/muss man bei bool Werten was beachten?

Danke. Gruß Christian

**Comment by aeberhard** [comment]
@darwin26 Hi Christian,

Ja, bisher werden alle Werte als Text gespeichert und auch als String zurückgeliefert.

Das ist übrigens ein Bug vom Codemirror, prüfe ich auch mal in der aktuellsten Version und fixe das wenn nötig. 

Gruß, Andreas

**Comment by darwin26** [comment]
HI.. dachte nur weil:

> property = Text -> (string) Text
> property = 1 -> (integer) 1
> property = 1.0 -> (float) 1
> property = 1,2 -> (float) 1.2
> property = 1.2-> (float) 1.2
> property = "asdf" -> (string) asdf
> property = '"asdf"' -> (string) "asdf"
> property = true -> (boolean) true
> propery = FALSE -> (boolean) false
> property = {"erstens": 1, "zweitens": 2} -> array(2) { ["erstens"]=> int(1) ["zweitens"]=> int(2) }

trotzdem -> Danke fürs AddOn! ist echt eine Bereicherung (Erleichterung)...

**Comment by aeberhard** [comment]
@darwin26 Das ist neu dazugekommen :)

**Comment by darwin26** [comment]
Danke!

**Comment by aeberhard** [comment]
Ich mach hier mal zu ...
