### ISSUE TITLE
Properties - Profil Erweiterung

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/properties#6]
Hi,
wäre evtl eine Idee, die properties mit einer ID zu erweitern.
Dann könnte man es (ähnl. tinymce oder ck editpr) die properties via ID abfragen und somit eine Art Manager zu erhalten. Sprich: properties der ID:xyz abrufen und der jeweiligen Site-Id zuweisen.

`rex::getProperty('HalloText', 9); # 1 wäre die ID des Property-Profils`

Wäre dann fast sowas wie ein "website-settings/properties-Manager" ;) ...
Danke. Gruß Christian

**Comment by aeberhard** [comment]
Hi @darwin26 ,

das ist nicht möglich da hier ja die REDAXO-Funktionalität verwendet wird. Müsste dann im Core geändert werden.
Aber das kann man ja auch über die Sections/Prefixe lösen. 

Gruß, Andreas

**Comment by aeberhard** [comment]
Hier mach ich auch mal zu!
