### ISSUE TITLE
Min-php version in package.yml notieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/properties#8]

**Comment by aeberhard** [comment]
@staabm Was ist denn deine Empfehlung Markus? '>=7.0' oder höher?

**Comment by staabm** [comment]
Jep, Z.b ^7.0

**Comment by aeberhard** [comment]
Ok, ist denn das mit den Versionsnummern (Syntax) irgendwo beschrieben? Was bedeutet ^?
Ist dann nur 7.0.xx möglich?

**Comment by staabm** [comment]
Hier findest du alles
https://getcomposer.org/doc/articles/versions.md

^7.0 bedeutet >=7.0 & <8.0

>= 7.0 hat das problem dass dort auch 8.0, 9.0 etc enthalten ist (keine obere grenze)

**Comment by aeberhard** [comment]
Ah danke! Sollte das auch in der Doku bei package.yml verlinkt werden!?

**Comment by staabm** [comment]
Gute Idee, Muss du @skerbis fragen :-)
